use mastet
GO
--CREAR LA BASE DE DATOS: BDEMPRESA ksnbd
CREATE DATABASE BDEMPRESA
GO
H
--ACTIVAR LA BASE DE DATOS
USE BDEMPRESA
GO

--CREAR LA TABLA ARTICULOS
CREATE TABLE ARTICULOS(
CODIGO CHAR(5) PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR (50) NOT NULL,
PRECIO DECIMAL NOT NULL,
STOCK INT NOT NULL
)

--VISUALIZAR LOS REGISTROS DE LA 
--TABLA ARTICULOS
SELECT*FROM ARTICULOS

--INSERTAR REGISTROS A LA TABLA
INSERT INTO ARTICULOS
VALUES('A001','TECLADO',12.5,100)
INSERT INTO ARTICULOS
VALUES('A002','MOUSE',15.5,300)
INSERT INTO ARTICULOS
VALUES('A003','PARLANTE',19.9,55)

--MODIFICAR EL STOCK DEL ARTICULO
--A001 POR 380

